DROP DATABASE IF EXISTS  autoquiray;

CREATE DATABASE autoquiray;

USE autoquiray;


CREATE TABLE users(
    DNI VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    type ENUM("student", "teacher", "administrator") NOT NULL
);

CREATE TABLE students(
    DNI VARCHAR(255) NOT NULL PRIMARY KEY,

    FOREIGN KEY (DNI) REFERENCES users(DNI)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE teachers(
    DNI VARCHAR(255) NOT NULL PRIMARY KEY,

    FOREIGN KEY (DNI) REFERENCES users(DNI)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE administrators(
    DNI VARCHAR(255) NOT NULL PRIMARY KEY,

    FOREIGN KEY (DNI) REFERENCES users(DNI)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);